/// Code Generated by Copilot b2c3d4e5-f6f7-8901-bcde-f1234567890ab. This comment will be removed automatically after the file is saved :::

#include <iostream>
#include <vector>
#include <cmath>
#include <chrono>
#include <cuda_runtime.h>

#define TILE_DIM 16
#define SIZE 3072

// ==================== Original Kernel ====================
__global__ void matmul_original(const float* A, const float* B, float* C, int M, int N, int K) {
    __shared__ float sh_a[TILE_DIM][TILE_DIM];
    __shared__ float sh_b[TILE_DIM][TILE_DIM];

    int row = blockIdx.y * blockDim.y + threadIdx.y;
    int col = blockIdx.x * blockDim.x + threadIdx.x;
    float sum = 0.0f;

    for (int tile = 0; tile < (N + TILE_DIM - 1) / TILE_DIM; ++tile) {
        int a_col = tile * TILE_DIM + threadIdx.x;
        int a_row = blockIdx.y * TILE_DIM + threadIdx.y;
        if (a_col < N && a_row < M) {
            sh_a[threadIdx.y][threadIdx.x] = A[a_row * N + a_col];
        } else {
            sh_a[threadIdx.y][threadIdx.x] = 0.0f;
        }

        int b_row = tile * TILE_DIM + threadIdx.y;
        int b_col = blockIdx.x * TILE_DIM + threadIdx.x;
        if (b_row < N && b_col < K) {
            sh_b[threadIdx.y][threadIdx.x] = B[b_row * K + b_col];
        } else {
            sh_b[threadIdx.y][threadIdx.x] = 0.0f;
        }
        __syncthreads();

        #pragma unroll
        for (int k = 0; k < TILE_DIM; ++k) {
            sum += sh_a[threadIdx.y][k] * sh_b[k][threadIdx.x];
        }
        __syncthreads();
    }

    if (row < M && col < K) {
        C[row * K + col] = sum;
    }
}

// ==================== Vectorized Kernel with LDG Cache ====================
// Uses __ldg for better cache performance and loop unrolling
__global__ void matmul_vectorized_ldg(const float* A, const float* B, float* C, int M, int N, int K) {
    __shared__ float sh_a[TILE_DIM][TILE_DIM + 1];  // +1 padding to avoid bank conflicts
    __shared__ float sh_b[TILE_DIM][TILE_DIM + 1];

    int row = blockIdx.y * blockDim.y + threadIdx.y;
    int col = blockIdx.x * blockDim.x + threadIdx.x;
    float sum = 0.0f;

    for (int tile = 0; tile < (N + TILE_DIM - 1) / TILE_DIM; ++tile) {
        // Use __ldg for better cache behavior on reads from global memory
        int a_col = tile * TILE_DIM + threadIdx.x;
        int a_row = blockIdx.y * TILE_DIM + threadIdx.y;
        if (a_col < N && a_row < M) {
            sh_a[threadIdx.y][threadIdx.x] = __ldg(&A[a_row * N + a_col]);
        } else {
            sh_a[threadIdx.y][threadIdx.x] = 0.0f;
        }

        int b_row = tile * TILE_DIM + threadIdx.y;
        int b_col = blockIdx.x * TILE_DIM + threadIdx.x;
        if (b_row < N && b_col < K) {
            sh_b[threadIdx.y][threadIdx.x] = __ldg(&B[b_row * K + b_col]);
        } else {
            sh_b[threadIdx.y][threadIdx.x] = 0.0f;
        }
        __syncthreads();

        // Fully unrolled compute loop with manual loop unrolling hints
        #pragma unroll 16
        for (int k = 0; k < TILE_DIM; ++k) {
            sum += sh_a[threadIdx.y][k] * sh_b[k][threadIdx.x];
        }
        __syncthreads();
    }

    if (row < M && col < K) {
        C[row * K + col] = sum;
    }
}

// ==================== Vectorized Kernel with Prefetching ====================
// Double-buffered shared memory with prefetching
__global__ void matmul_vectorized_prefetch(const float* A, const float* B, float* C, int M, int N, int K) {
    __shared__ float sh_a[2][TILE_DIM][TILE_DIM + 1];  // Double buffering
    __shared__ float sh_b[2][TILE_DIM][TILE_DIM + 1];

    int row = blockIdx.y * blockDim.y + threadIdx.y;
    int col = blockIdx.x * blockDim.x + threadIdx.x;
    float sum = 0.0f;

    int num_tiles = (N + TILE_DIM - 1) / TILE_DIM;

    // Preload first tile
    int a_col = threadIdx.x;
    int a_row = blockIdx.y * TILE_DIM + threadIdx.y;
    if (a_col < N && a_row < M) {
        sh_a[0][threadIdx.y][threadIdx.x] = A[a_row * N + a_col];
    } else {
        sh_a[0][threadIdx.y][threadIdx.x] = 0.0f;
    }

    int b_row = threadIdx.y;
    int b_col = blockIdx.x * TILE_DIM + threadIdx.x;
    if (b_row < N && b_col < K) {
        sh_b[0][threadIdx.y][threadIdx.x] = B[b_row * K + b_col];
    } else {
        sh_b[0][threadIdx.y][threadIdx.x] = 0.0f;
    }
    __syncthreads();

    for (int tile = 0; tile < num_tiles; ++tile) {
        int curr = tile & 1;
        int next = 1 - curr;

        // Prefetch next tile while computing current
        if (tile + 1 < num_tiles) {
            int next_a_col = (tile + 1) * TILE_DIM + threadIdx.x;
            if (next_a_col < N && a_row < M) {
                sh_a[next][threadIdx.y][threadIdx.x] = A[a_row * N + next_a_col];
            } else {
                sh_a[next][threadIdx.y][threadIdx.x] = 0.0f;
            }

            int next_b_row = (tile + 1) * TILE_DIM + threadIdx.y;
            if (next_b_row < N && b_col < K) {
                sh_b[next][threadIdx.y][threadIdx.x] = B[next_b_row * K + b_col];
            } else {
                sh_b[next][threadIdx.y][threadIdx.x] = 0.0f;
            }
        }
        __syncthreads();

        // Compute with current tile
        #pragma unroll 16
        for (int k = 0; k < TILE_DIM; ++k) {
            sum += sh_a[curr][threadIdx.y][k] * sh_b[curr][k][threadIdx.x];
        }
        __syncthreads();
    }

    if (row < M && col < K) {
        C[row * K + col] = sum;
    }
}


// --- CPU Version for Comparison ---
void matmul_cpu(const float* A, const float* B, float* C, int M, int N, int K) {
    for (int i = 0; i < M; ++i) {
        for (int j = 0; j < K; ++j) {
            float sum = 0.0f;
            for (int k = 0; k < N; ++k) {
                sum += A[i * N + k] * B[k * K + j];
            }
            C[i * K + j] = sum;
        }
    }
}

// --- Verification Helper ---
bool verify_results(const float* gpu_res1, const float* gpu_res2, int size) {
    for (int i = 0; i < size; ++i) {
        if (std::fabs(gpu_res1[i] - gpu_res2[i]) > 1e-2f) {
            return false;
        }
    }
    return true;
}

int main() {
    const int M = SIZE;
    const int N = SIZE;
    const int K = SIZE;

    size_t size_A = M * N * sizeof(float);
    size_t size_B = N * K * sizeof(float);
    size_t size_C = M * K * sizeof(float);

    std::vector<float> h_A(M * N), h_B(N * K), h_C_gpu_orig(M * K), h_C_gpu_ldg(M * K), h_C_gpu_pref(M * K);

    // Initialize matrices
    for (int i = 0; i < M * N; ++i) h_A[i] = static_cast<float>(rand()) / RAND_MAX;
    for (int i = 0; i < N * K; ++i) h_B[i] = static_cast<float>(rand()) / RAND_MAX;

    // Device memory
    float *d_A, *d_B, *d_C_orig, *d_C_ldg, *d_C_pref;
    cudaMalloc(&d_A, size_A);
    cudaMalloc(&d_B, size_B);
    cudaMalloc(&d_C_orig, size_C);
    cudaMalloc(&d_C_ldg, size_C);
    cudaMalloc(&d_C_pref, size_C);

    // Copy data to device
    cudaMemcpy(d_A, h_A.data(), size_A, cudaMemcpyHostToDevice);
    cudaMemcpy(d_B, h_B.data(), size_B, cudaMemcpyHostToDevice);

    // Setup grid/block dimensions
    dim3 block(16, 16);
    dim3 grid((K + TILE_DIM - 1) / TILE_DIM, (M + TILE_DIM - 1) / TILE_DIM);

    // Warmup
    matmul_original<<<grid, block>>>(d_A, d_B, d_C_orig, M, N, K);
    cudaDeviceSynchronize();

    // Benchmark Original Kernel
    const int iterations = 100;
    auto start = std::chrono::high_resolution_clock::now();
    for (int i = 0; i < iterations; ++i) {
        matmul_original<<<grid, block>>>(d_A, d_B, d_C_orig, M, N, K);
    }
    cudaDeviceSynchronize();
    auto end = std::chrono::high_resolution_clock::now();
    double time_orig_ms = std::chrono::duration<double, std::milli>(end - start).count() / iterations;

    // Benchmark LDG + Padding Kernel
    start = std::chrono::high_resolution_clock::now();
    for (int i = 0; i < iterations; ++i) {
        matmul_vectorized_ldg<<<grid, block>>>(d_A, d_B, d_C_ldg, M, N, K);
    }
    cudaDeviceSynchronize();
    end = std::chrono::high_resolution_clock::now();
    double time_ldg_ms = std::chrono::duration<double, std::milli>(end - start).count() / iterations;

    // Benchmark Prefetch + Double-Buffering Kernel
    start = std::chrono::high_resolution_clock::now();
    for (int i = 0; i < iterations; ++i) {
        matmul_vectorized_prefetch<<<grid, block>>>(d_A, d_B, d_C_pref, M, N, K);
    }
    cudaDeviceSynchronize();
    end = std::chrono::high_resolution_clock::now();
    double time_pref_ms = std::chrono::duration<double, std::milli>(end - start).count() / iterations;

    // Copy results back
    cudaMemcpy(h_C_gpu_orig.data(), d_C_orig, size_C, cudaMemcpyDeviceToHost);
    cudaMemcpy(h_C_gpu_ldg.data(), d_C_ldg, size_C, cudaMemcpyDeviceToHost);
    cudaMemcpy(h_C_gpu_pref.data(), d_C_pref, size_C, cudaMemcpyDeviceToHost);

    // Display results
    std::cout << "\n=== Matrix Multiplication Optimization Comparison ===" << std::endl;
    std::cout << "Matrix Size: " << M << " x " << N << " * " << N << " x " << K << " = " << M << " x " << K << std::endl;
    std::cout << "Kernel Launches: " << iterations << " iterations" << std::endl;
    
    std::cout << "\n[1] Original Kernel (Baseline)" << std::endl;
    std::cout << "    Time: " << time_orig_ms << " ms" << std::endl;
    std::cout << "    GFLOPS: " << (2.0 * M * N * K) / (time_orig_ms * 1e-3) / 1e9 << std::endl;

    std::cout << "\n[2] LDG + Shared Memory Padding Optimization" << std::endl;
    std::cout << "    Time: " << time_ldg_ms << " ms" << std::endl;
    std::cout << "    GFLOPS: " << (2.0 * M * N * K) / (time_ldg_ms * 1e-3) / 1e9 << std::endl;
    std::cout << "    Speedup: " << time_orig_ms / time_ldg_ms << "x" << std::endl;
    std::cout << "    Change: " << ((time_ldg_ms / time_orig_ms - 1.0) * 100) << "%" << std::endl;

    std::cout << "\n[3] Double-Buffered Prefetch Optimization" << std::endl;
    std::cout << "    Time: " << time_pref_ms << " ms" << std::endl;
    std::cout << "    GFLOPS: " << (2.0 * M * N * K) / (time_pref_ms * 1e-3) / 1e9 << std::endl;
    std::cout << "    Speedup: " << time_orig_ms / time_pref_ms << "x" << std::endl;
    std::cout << "    Change: " << ((time_pref_ms / time_orig_ms - 1.0) * 100) << "%" << std::endl;

    std::cout << "\n--- Verification ---" << std::endl;
    std::cout << "Original vs LDG: " << (verify_results(h_C_gpu_orig.data(), h_C_gpu_ldg.data(), M * K) ? "PASS ✓" : "FAIL ✗") << std::endl;
    std::cout << "Original vs Prefetch: " << (verify_results(h_C_gpu_orig.data(), h_C_gpu_pref.data(), M * K) ? "PASS ✓" : "FAIL ✗") << std::endl;

    std::cout << "\n=== Analysis ===" << std::endl;
    std::cout << "• LDG reads: Improves cache hit rate on global memory reads" << std::endl;
    std::cout << "• Bank conflict avoidance: Padding +1 in shared memory reduces conflicts" << std::endl;
    std::cout << "• Double-buffering: Enables computation-communication overlap" << std::endl;
    std::cout << "• Best optimization: " << (time_ldg_ms < time_pref_ms ? "LDG + Padding" : "Double-Buffering") << std::endl;

    // Cleanup
    cudaFree(d_A);
    cudaFree(d_B);
    cudaFree(d_C_orig);
    cudaFree(d_C_ldg);
    cudaFree(d_C_pref);

    return 0;
}

